USE Practica1;

DROP TABLE IF EXISTS level_1a;
DROP TABLE IF EXISTS geoname;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS countrycodes;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS currency;